name: Sync to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 6 # Automatically cancels the job if it hangs past 6 minutes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Sync to Hugging Face Spaces
        uses: JacobLinCool/huggingface-sync@v1
        with:
          github: ${{ secrets.GITHUB_TOKEN }}
          user: iamfebin
          space: automated-german-news-pipeline
          token: ${{ secrets.HF_WRITE_TOKEN || secrets.HF_TOKEN }}
          configuration: "README.md.yml"
